In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("ai_job_dataset.csv")

In [4]:
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  str
 1   job_title               15000 non-null  str
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  str
 4   experience_level        15000 non-null  str
 5   employment_type         15000 non-null  str
 6   company_location        15000 non-null  str
 7   company_size            15000 non-null  str
 8   employee_residence      15000 non-null  str
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  str
 11  education_required      15000 non-null  str
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  str
 14  posting_date            15000 non-null  str
 15  application_deadline    15000 non-null  str
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  str
dtypes: float64(1), int64(4), str(14)
memory usage: 4.1 MB

In [6]:
df.describe()

,salary_usd,remote_ratio,years_experience,job_description_length,benefits_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,115348.965133,49.483333,6.253200,1503.314733,7.504273
std,60260.940438,40.812712,5.545768,576.127083,1.450870
min,32519.000000,0.000000,0.000000,500.000000,5.000000
25%,70179.750000,0.000000,2.000000,1003.750000,6.200000
50%,99705.000000,50.000000,5.000000,1512.000000,7.500000
75%,146408.500000,100.000000,10.000000,2000.000000,8.800000
max,399095.000000,100.000000,19.000000,2499.000000,10.000000

In [7]:
import plotly.express as px

In [10]:
df.select_dtypes(include='number').columns

Index(['salary_usd', 'remote_ratio', 'years_experience',
       'job_description_length', 'benefits_score'],
      dtype='str')

In [17]:
for column in df.select_dtypes(exclude='O').columns:
    fig = px.box(df, x=column, title=column)
    fig.show()

In [15]:
px.box(df, x='salary_usd')

In [18]:
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [21]:
df.drop(['job_id', 'salary_currency', 'employee_residence', 'industry',
         'application_deadline', 'posting_date', 'job_description_length', 'benefits_score'], axis=1, inplace=True)

In [22]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name
0,AI Research Scientist,90376,SE,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics
1,AI Software Engineer,61895,EN,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc
2,AI Specialist,152626,MI,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech
3,NLP Engineer,80215,SE,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Future Systems
4,AI Consultant,54624,EN,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics

In [27]:
def exp_level(any_value):
    if any_value == 'SE':
        return 'Senior'
    elif any_value == 'EN':
        return  'Entry'
    elif any_value == 'MI':
        return 'Mid-level'
    else:
        return 'Excutive'

In [28]:
exp_level('SE')

'Senior'

In [30]:
df.experience_level = df.experience_level.apply(exp_level)

In [31]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name
0,AI Research Scientist,90376,Senior,CT,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics
1,AI Software Engineer,61895,Entry,CT,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc
2,AI Specialist,152626,Mid-level,FL,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech
3,NLP Engineer,80215,Senior,FL,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Future Systems
4,AI Consultant,54624,Entry,PT,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics

In [33]:
df.employment_type = df.employment_type.apply(lambda x:'Full Time' if x == 'FT' else 'Part Time' if x == 'PT' else 'Contract' if x == 'CT' else 'Freelance')

In [34]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name
0,AI Research Scientist,90376,Senior,Contract,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics
1,AI Software Engineer,61895,Entry,Contract,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc
2,AI Specialist,152626,Mid-level,Freelance,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech
3,NLP Engineer,80215,Senior,Freelance,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Future Systems
4,AI Consultant,54624,Entry,Part Time,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics

In [35]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name
0,AI Research Scientist,90376,Senior,Contract,China,M,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics
1,AI Software Engineer,61895,Entry,Contract,Canada,M,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc
2,AI Specialist,152626,Mid-level,Freelance,Switzerland,L,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech
3,NLP Engineer,80215,Senior,Freelance,India,M,50,"Scala, SQL, Linux, Python",PhD,7,Future Systems
4,AI Consultant,54624,Entry,Part Time,France,S,100,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics

In [41]:
def change_company_size(company_name):
    if company_name == "S":
        return "Small <50"
    elif company_name == "M":
        return "Medium 50-250"
    else:
        return "Large >250"

In [43]:
df.company_size = df.company_size.apply(change_company_size)

In [45]:
df.remote_ratio = df.remote_ratio.apply(lambda X : "No Remote" if X == 0 else "Hyrid" if X == 50 else "Remote")

In [46]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Hyrid,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Remote,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc
2,AI Specialist,152626,Mid-level,Freelance,Switzerland,Large >250,No Remote,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,Hyrid,"Scala, SQL, Linux, Python",PhD,7,Future Systems
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Remote,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics

In [63]:
total_skills = []
for item in df.required_skills.apply(lambda x: x.split(', ')):
    for skill in item:
        total_skills.append(skill)


total_skills

['Tableau',
 'PyTorch',
 'Kubernetes',
 'Linux',
 'NLP',
 'Deep Learning',
 'AWS',
 'Mathematics',
 'Python',
 'Docker',
 'Kubernetes',
 'Deep Learning',
 'Java',
 'Hadoop',
 'NLP',
 'Scala',
 'SQL',
 'Linux',
 'Python',
 'MLOps',
 'Java',
 'Tableau',
 'Python',
 'Data Visualization',
 'R',
 'SQL',
 'Linux',
 'R',
 'Docker',
 'MLOps',
 'Python',
 'SQL',
 'Computer Vision',
 'Java',
 'Azure',
 'Hadoop',
 'Git',
 'Mathematics',
 'Python',
 'MLOps',
 'GCP',
 'Scala',
 'Azure',
 'Linux',
 'MLOps',
 'Python',
 'SQL',
 'R',
 'Data Visualization',
 'Python',
 'Azure',
 'Tableau',
 'Python',
 'TensorFlow',
 'Scala',
 'SQL',
 'Statistics',
 'PyTorch',
 'Python',
 'Data Visualization',
 'GCP',
 'Linux',
 'Statistics',
 'Deep Learning',
 'Tableau',
 'NLP',
 'Spark',
 'MLOps',
 'PyTorch',
 'Azure',
 'Git',
 'Hadoop',
 'R',
 'Python',
 'Spark',
 'Java',
 'Scala',
 'NLP',
 'Docker',
 'Computer Vision',
 'Deep Learning',
 'AWS',
 'Azure',
 'Tableau',
 'Spark',
 'NLP',
 'TensorFlow',
 'PyTorch',
 'Hadoop',
 'Git',
 'Tableau',
 'Git',
 'Hadoop',
 'Docker',
 'AWS',
 'Azure',
 'Git',
 'SQL',
 'Computer Vision',
 'Linux',
 'Git',
 'Tableau',
 'Kubernetes',
 'Data Visualization',
 'Hadoop',
 'Linux',
 'Git',
 'Scala',
 'Mathematics',
 'Kubernetes',
 'TensorFlow',
 'Tableau',
 'PyTorch',
 'Python',
 'Scala',
 'NLP',
 'Mathematics',
 'Git',
 'Azure',
 'Python',
 'Computer Vision',
 'Kubernetes',
 'TensorFlow',
 'Deep Learning',
 'GCP',
 'AWS',
 'Linux',
 'Tableau',
 'Azure',
 'Python',
 'Spark',
 'NLP',
 'Scala',
 'Python',
 'Tableau',
 'Azure',
 'GCP',
 'Linux',
 'Python',
 'R',
 'GCP',
 'MLOps',
 'Linux',
 'Git',
 'Hadoop',
 'Data Visualization',
 'Data Visualization',
 'Tableau',
 'AWS',
 'Mathematics',
 'Python',
 'Linux',
 'PyTorch',
 'SQL',
 'Statistics',
 'Tableau',
 'Docker',
 'GCP',
 'Computer Vision',
 'Azure',
 'Tableau',
 'Data Visualization',
 'Azure',
 'Spark',
 'MLOps',
 'Java',
 'Mathematics',
 'SQL',
 'Spark',
 'Mathematics',
 'GCP',
 'Hadoop',
 'Docker',
 'Python',
 'Azure',
 'Docker',
 'R',
 'Linux',
 'Data Visualization',
 'Statistics',
 'R',
 'Scala',
 'Java',
 'Tableau',
 'Java',
 'Azure',
 'GCP',
 'Deep Learning',
 'Git',
 'Data Visualization',
 'Linux',
 'Java',
 'Hadoop',
 'AWS',
 'Linux',
 'Docker',
 'Statistics',
 'Deep Learning',
 'SQL',
 'Mathematics',
 'Linux',
 'R',
 'Azure',
 'Mathematics',
 'Git',
 'Docker',
 'Tableau',
 'Mathematics',
 'R',
 'PyTorch',
 'Kubernetes',
 'Computer Vision',
 'Python',
 'Tableau',
 'TensorFlow',
 'AWS',
 'Azure',
 'Kubernetes',
 'TensorFlow',
 'Statistics',
 'Spark',
 'Python',
 'Docker',
 'GCP',
 'Scala',
 'Git',
 'Linux',
 'Python',
 'TensorFlow',
 'Mathematics',
 'PyTorch',
 'Computer Vision',
 'R',
 'R',
 'Spark',
 'AWS',
 'Tableau',
 'NLP',
 'Azure',
 'Statistics',
 'PyTorch',
 'TensorFlow',
 'Azure',
 'Computer Vision',
 'Data Visualization',
 'TensorFlow',
 'Scala',
 'Docker',
 'Statistics',
 'Java',
 'R',
 'Deep Learning',
 'NLP',
 'Azure',
 'Java',
 'Git',
 'Deep Learning',
 'Mathematics',
 'Spark',
 'Python',
 'AWS',
 'SQL',
 'Java',
 'MLOps',
 'Linux',
 'PyTorch',
 'Python',
 'Scala',
 'Statistics',
 'Git',
 'Hadoop',
 'Python',
 'Kubernetes',
 'Azure',
 'MLOps',
 'Kubernetes',
 'Git',
 'Python',
 'AWS',
 'Kubernetes',
 'Azure',
 'PyTorch',
 'Kubernetes',
 'Git',
 'SQL',
 'NLP',
 'Azure',
 'Statistics',
 'Spark',
 'Mathematics',
 'Linux',
 'R',
 'Tableau',
 'Scala',
 'R',
 'Tableau',
 'Data Visualization',
 'Mathematics',
 'Kubernetes',
 'Spark',
 'Kubernetes',
 'Spark',
 'Statistics',
 'Scala',
 'MLOps',
 'SQL',
 'Statistics',
 'Scala',
 'MLOps',
 'NLP',
 'PyTorch',
 'Linux',
 'SQL',
 'Git',
 'Kubernetes',
 'TensorFlow',
 'R',
 'Java',
 'R',
 'Tableau',
 'SQL',
 'MLOps',
 'Docker',
 'NLP',
 'Azure',
 'Spark',
 'Data Visualization',
 'Java',
 'SQL',
 'Spark',
 'Tableau',
 'Azure',
 'Docker',
 'Python',
 'Git',
 'Kubernetes',
 'Java',
 'Git',
 'MLOps',
 'Hadoop',
 'Python',
 'Spark',
 'SQL',
 'Kubernetes',
 'Docker',
 'R',
 'NLP',
 'SQL',
 'GCP',
 'Spark',
 'SQL',
 'Python',
 'Mathematics',
 'Linux',
 'PyTorch',
 'Hadoop',
 'Scala',
 'Computer Vision',
 'Hadoop',
 'Spark',
 'Kubernetes',
 'Python',
 'Hadoop',
 'Python',
 'TensorFlow',
 'R',
 'Statistics',
 'Computer Vision',
 'PyTorch',
 'GCP',
 'Linux',
 'Java',
 'Hadoop',
 'Mathematics',
 'Linux',
 'R',
 'NLP',
 'PyTorch',
 'Git',
 'Statistics',
 'Python',
 'TensorFlow',
 'PyTorch',
 'Git',
 'Kubernetes',
 'Scala',
 'Java',
 'Deep Learning',
 'Statistics',
 'Computer Vision',
 'TensorFlow',
 'Mathematics',
 'Python',
 'AWS',
 'Kubernetes',
 'Deep Learning',
 'AWS',
 'Kubernetes',
 'Docker',
 'Mathematics',
 'MLOps',
 'Scala',
 'Git',
 'Java',
 'Azure',
 'AWS',
 'PyTorch',
 'GCP',
 'Hadoop',
 'Spark',
 'Mathematics',
 'PyTorch',
 'SQL',
 'TensorFlow',
 'SQL',
 'Python',
 'Deep Learning',
 'TensorFlow',
 'GCP',
 'PyTorch',
 'Spark',
 'Git',
 'SQL',
 'PyTorch',
 'Mathematics',
 'Data Visualization',
 'PyTorch',
 'Spark',
 'TensorFlow',
 'TensorFlow',
 'SQL',
 'NLP',
 'Computer Vision',
 'Git',
 'Java',
 'R',
 'Git',
 'Mathematics',
 'Spark',
 'PyTorch',
 'Docker',
 'GCP',
 'Computer Vision',
 'Hadoop',
 'Git',
 'AWS',
 'TensorFlow',
 'Linux',
 'SQL',
 'Hadoop',
 'SQL',
 'Scala',
 'Python',
 'NLP',
 'Computer Vision',
 'Mathematics',
 'Statistics',
 'R',
 'Azure',
 'R',
 'Linux',
 'MLOps',
 'R',
 'AWS',
 'Computer Vision',
 'Statistics',
 'Docker',
 'Kubernetes',
 'SQL',
 'Azure',
 'Deep Learning',
 'Linux',
 'PyTorch',
 'SQL',
 'MLOps',
 'AWS',
 'TensorFlow',
 'MLOps',
 'R',
 'Git',
 'Mathematics',
 'Linux',
 'Scala',
 'SQL',
 'Git',
 'Git',
 'Deep Learning',
 'Kubernetes',
 'Linux',
 'GCP',
 'Git',
 'SQL',
 'Scala',
 'Python',
 'Computer Vision',
 'Python',
 'Tableau',
 'Java',
 'Docker',
 'AWS',
 'Linux',
 'Git',
 'Azure',
 'PyTorch',
 'Scala',
 'Linux',
 'Tableau',
 'Deep Learning',
 'Docker',
 'SQL',
 'Kubernetes',
 'Git',
 'Statistics',
 'Statistics',
 'R',
 'Python',
 'TensorFlow',
 'Kubernetes',
 'Azure',
 'Spark',
 'TensorFlow',
 'Linux',
 'GCP',
 'R',
 'Azure',
 'Deep Learning',
 'PyTorch',
 'Spark',
 'Python',
 'Deep Learning',
 'Linux',
 'Java',
 'AWS',
 'R',
 'Spark',
 'Python',
 'TensorFlow',
 'PyTorch',
 'Statistics',
 'Python',
 'SQL',
 'Hadoop',
 'Azure',
 'Python',
 'R',
 'Computer Vision',
 'GCP',
 'Azure',
 'SQL',
 'Python',
 'Hadoop',
 'Java',
 'Data Visualization',
 'Computer Vision',
 'SQL',
 'PyTorch',
 'Java',
 'Hadoop',
 'Python',
 'Git',
 'TensorFlow',
 'PyTorch',
 'Statistics',
 'MLOps',
 'Kubernetes',
 'Computer Vision',
 'Linux',
 'AWS',
 'Computer Vision',
 'Deep Learning',
 'PyTorch',
 'TensorFlow',
 'Hadoop',
 'Python',
 'GCP',
 'Kubernetes',
 'Computer Vision',
 'Deep Learning',
 'SQL',
 'SQL',
 'MLOps',
 'Python',
 'Python',
 'Hadoop',
 'Deep Learning',
 'GCP',
 'Linux',
 'R',
 'Hadoop',
 'TensorFlow',
 'Git',
 'Azure',
 'Python',
 'Kubernetes',
 'Deep Learning',
 'PyTorch',
 'SQL',
 'Data Visualization',
 'GCP',
 'Deep Learning',
 'MLOps',
 'GCP',
 'Python',
 'Computer Vision',
 'Git',
 'TensorFlow',
 'Kubernetes',
 'Deep Learning',
 'Computer Vision',
 'PyTorch',
 'Linux',
 'TensorFlow',
 'Git',
 'Tableau',
 'Hadoop',
 'Computer Vision',
 'R',
 'SQL',
 'Data Visualization',
 'Linux',
 'Python',
 'Scala',
 'Docker',
 'Python',
 'GCP',
 'TensorFlow',
 'Docker',
 'Deep Learning',
 'R',
 'Git',
 'Spark',
 'Azure',
 'Statistics',
 'Python',
 'Java',
 'Kubernetes',
 'SQL',
 'NLP',
 'Hadoop',
 'Mathematics',
 'Linux',
 'GCP',
 'Computer Vision',
 'Scala',
 'AWS',
 'Linux',
 'Data Visualization',
 'SQL',
 'Scala',
 'SQL',
 'Tableau',
 'Statistics',
 'GCP',
 'Deep Learning',
 'Python',
 'NLP',
 'R',
 'AWS',
 'Git',
 'Tableau',
 'Python',
 'Spark',
 'Hadoop',
 'Linux',
 'TensorFlow',
 'GCP',
 'Docker',
 'Azure',
 'TensorFlow',
 'Docker',
 'AWS',
 'Spark',
 'Linux',
 'Azure',
 'Kubernetes',
 'Statistics',
 'Tableau',
 'Java',
 'Data Visualization',
 'NLP',
 'Spark',
 'Linux',
 'AWS',
 'Deep Learning',
 'Scala',
 'Data Visualization',
 'TensorFlow',
 'Mathematics',
 'Java',
 'PyTorch',
 'Scala',
 'Hadoop',
 'Docker',
 'Computer Vision',
 'Tableau',
 'GCP',
 'Python',
 'Python',
 'TensorFlow',
 'GCP',
 'Java',
 'Statistics',
 'TensorFlow',
 'Python',
 'Scala',
 'Hadoop',
 'Azure',
 'Linux',
 'Azure',
 'Git',
 'Deep Learning',
 'Spark',
 'Kubernetes',
 'Git',
 'GCP',
 'NLP',
 'Scala',
 'Python',
 'Data Visualization',
 'Kubernetes',
 'Statistics',
 'Deep Learning',
 'Azure',
 'Python',
 'Statistics',
 'AWS',
 'Java',
 'PyTorch',
 'Python',
 'Spark',
 'TensorFlow',
 'SQL',
 'Docker',
 'Linux',
 'GCP',
 'PyTorch',
 'NLP',
 'MLOps',
 'Azure',
 'Docker',
 'Azure',
 'NLP',
 'Python',
 'TensorFlow',
 'R',
 'SQL',
 'PyTorch',
 'NLP',
 'Data Visualization',
 'Java',
 'Python',
 'Mathematics',
 'Mathematics',
 'Docker',
 'Deep Learning',
 'NLP',
 'R',
 'Scala',
 'Computer Vision',
 'Azure',
 'Python',
 'TensorFlow',
 'Scala',
 'AWS',
 'PyTorch',
 'SQL',
 'Kubernetes',
 'Git',
 'Java',
 'Java',
 'Python',
 'Deep Learning',
 'Statistics',
 'TensorFlow',
 'Docker',
 'R',
 'NLP',
 'Java',
 'Java',
 'Scala',
 'Tableau',
 'GCP',
 'TensorFlow',
 'Data Visualization',
 'Linux',
 'PyTorch',
 'TensorFlow',
 'Azure',
 'Python',
 'MLOps',
 'Python',
 'Linux',
 'NLP',
 'Linux',
 'Kubernetes',
 'Spark',
 'Java',
 'TensorFlow',
 'Kubernetes',
 'SQL',
 'Linux',
 'Mathematics',
 'MLOps',
 'Java',
 'AWS',
 'NLP',
 'PyTorch',
 'Statistics',
 'Python',
 'TensorFlow',
 'PyTorch',
 'SQL',
 'TensorFlow',
 'Git',
 'Azure',
 'Scala',
 'SQL',
 'Deep Learning',
 'Statistics',
 'GCP',
 'AWS',
 'Scala',
 'Docker',
 'Spark',
 'Kubernetes',
 'Mathematics',
 'Python',
 'SQL',
 'Git',
 'Python',
 'GCP',
 'Docker',
 'Git',
 'Java',
 'Mathematics',
 'Hadoop',
 'Tableau',
 'Linux',
 'Python',
 'NLP',
 'Java',
 'Docker',
 'Hadoop',
 'Python',
 'Kubernetes',
 'Statistics',
 'TensorFlow',
 'GCP',
 'Deep Learning',
 'Python',
 'MLOps',
 'R',
 'SQL',
 'AWS',
 'MLOps',
 'Data Visualization',
 'Azure',
 'Python',
 'TensorFlow',
 'Data Visualization',
 'GCP',
 'Azure',
 'Deep Learning',
 'Spark',
 'SQL',
 'MLOps',
 'Data Visualization',
 'Git',
 'TensorFlow',
 'Hadoop',
 'R',
 'Docker',
 'GCP',
 'Java',
 'PyTorch',
 'MLOps',
 'Computer Vision',
 'AWS',
 'Deep Learning',
 'AWS',
 'Hadoop',
 'Python',
 'Scala',
 'Computer Vision',
 'PyTorch',
 'SQL',
 'Kubernetes',
 'SQL',
 'Linux',
 'Tableau',
 'MLOps',
 'Spark',
 'Mathematics',
 'Hadoop',
 'Scala',
 'NLP',
 'Kubernetes',
 'Scala',
 'R',
 'SQL',
 'Java',
 'Python',
 'MLOps',
 'Docker',
 'SQL',
 'NLP',
 'Python',
 'Data Visualization',
 'Linux',
 'GCP',
 'Hadoop',
 'Hadoop',
 'Python',
 'Linux',
 'Mathematics',
 'Kubernetes',
 'Linux',
 'Tableau',
 'MLOps',
 'Statistics',
 'Docker',
 'PyTorch',
 'Spark',
 'TensorFlow',
 'NLP',
 'Tableau',
 'Linux',
 'PyTorch',
 'Java',
 'AWS',
 'Azure',
 'Python',
 'Mathematics',
 'TensorFlow',
 'Linux',
 'Deep Learning',
 'Hadoop',
 'TensorFlow',
 'Azure',
 'Tableau',
 'Data Visualization',
 'Hadoop',
 'NLP',
 'Tableau',
 'Kubernetes',
 'SQL',
 'GCP',
 'Scala',
 'Python',
 'Data Visualization',
 'Hadoop',
 'Spark',
 'Kubernetes',
 'Scala',
 'Linux',
 'Kubernetes',
 'Data Visualization',
 'TensorFlow',
 'Docker',
 'Git',
 'Statistics',
 'Data Visualization',
 'Python',
 'Scala',
 'Hadoop',
 'Spark',
 'Tableau',
 'R',
 'Python',
 'TensorFlow',
 'MLOps',
 'Kubernetes',
 'SQL',
 'Java',
 'Hadoop',
 'Azure',
 'Java',
 'MLOps',
 'Git',
 'Docker',
 'Statistics',
 'Mathematics',
 'Spark',
 'Git',
 'Hadoop',
 'Python',
 'Mathematics',
 'PyTorch',
 'Spark',
 'R',
 'Azure',
 'MLOps',
 'Git',
 'Statistics',
 'Mathematics',
 'Hadoop',
 'Java',
 'SQL',
 'Statistics',
 'Mathematics',
 ...]

In [69]:
pd.Series(total_skills).value_counts().reset_index().head()

        index  count
0      Python   4450
1         SQL   3407
2  TensorFlow   3022
3  Kubernetes   3009
4       Scala   2794

In [79]:
df['monthly_salary'] = (df.salary_usd / 12).astype(int)

In [80]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name,monthly_salary
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Hyrid,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics,7531
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Remote,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc,5157
2,AI Specialist,152626,Mid-level,Freelance,Switzerland,Large >250,No Remote,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech,12718
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,Hyrid,"Scala, SQL, Linux, Python",PhD,7,Future Systems,6684
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Remote,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics,4552

In [89]:
total_skills = []
for item in df.required_skills.apply(lambda x: x.split(', ')):
    for skill in item :
        total_skills.append(skill)

In [92]:
pd.Series(total_skills).value_counts().reset_index()

                 index  count
0               Python   4450
1                  SQL   3407
2           TensorFlow   3022
3           Kubernetes   3009
4                Scala   2794
5              PyTorch   2777
6                Linux   2705
7                  Git   2631
8                 Java   2578
9                  GCP   2442
10              Hadoop   2419
11             Tableau   2341
12                   R   2311
13     Computer Vision   2284
14  Data Visualization   2270
15       Deep Learning   2189
16               MLOps   2164
17               Spark   2155
18                 NLP   2145
19               Azure   2144
20                 AWS   2018
21         Mathematics   1943
22              Docker   1862
23          Statistics   1833

In [100]:
df['monthly_salary'] = (df.salary_usd/12).astype(int)

In [99]:
df.head()

,job_title,salary_usd,experience_level,employment_type,company_location,company_size,remote_ratio,required_skills,education_required,years_experience,company_name,monthly_salary
0,AI Research Scientist,90376,Senior,Contract,China,Medium 50-250,Hyrid,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Smart Analytics,7531
1,AI Software Engineer,61895,Entry,Contract,Canada,Medium 50-250,Remote,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,TechCorp Inc,5157
2,AI Specialist,152626,Mid-level,Freelance,Switzerland,Large >250,No Remote,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Autonomous Tech,12718
3,NLP Engineer,80215,Senior,Freelance,India,Medium 50-250,Hyrid,"Scala, SQL, Linux, Python",PhD,7,Future Systems,6684
4,AI Consultant,54624,Entry,Part Time,France,Small <50,Remote,"MLOps, Java, Tableau, Python",Master,0,Advanced Robotics,4552